### Function main that will allow to call the LeftRotation class

from LeftRotation import LeftRotation
import sys

if __name__ == '__main__':
    """
    Argv is equal to a list of string containing the input 
    typed by the user in the command line when calling the module 
    from the terminal.

    For example, python -m main abcde 3 will generate
    the following list : [path_file, 'abcde', '3']
    """

    chaine_de_caractere = sys.argv[1]
    nb_de_rotation = int(sys.argv[2]) # Initially, the data generated by argv are strings
    left_rotation = LeftRotation()
    print(left_rotation.rotate(chaine_de_caractere, nb_de_rotation))